class_name MouseMapEnum

enum ButtonMap
{
	NONE = MOUSE_BUTTON_NONE,
	LEFT = MOUSE_BUTTON_LEFT,
	RIGHT = MOUSE_BUTTON_RIGHT,
	MIDDLE = MOUSE_BUTTON_MIDDLE,
	WHEEL_UP = MOUSE_BUTTON_WHEEL_UP,
	WHEEL_DOWN = MOUSE_BUTTON_WHEEL_DOWN,
	WHEEL_LEFT = MOUSE_BUTTON_WHEEL_LEFT,
	WHEEL_RIGHT = MOUSE_BUTTON_WHEEL_RIGHT,
	XBUTTON1 = MOUSE_BUTTON_XBUTTON1,
	XBUTTON2 = MOUSE_BUTTON_XBUTTON2
}
