class_name JoypadMapEnum

enum ButtonMap
{
	INVALID = JOY_BUTTON_INVALID,
	A = JOY_BUTTON_A,
	B = JOY_BUTTON_B,
	X = JOY_BUTTON_X,
	Y = JOY_BUTTON_Y,
	BACK = JOY_BUTTON_BACK,
	GUIDE = JOY_BUTTON_GUIDE,
	START = JOY_BUTTON_START,
	LEFT_STICK = JOY_BUTTON_LEFT_STICK,
	RIGHT_STICK = JOY_BUTTON_RIGHT_STICK,
	LEFT_SHOULDER = JOY_BUTTON_LEFT_SHOULDER,
	RIGHT_SHOULDER = JOY_BUTTON_RIGHT_SHOULDER,
	DPAD_UP = JOY_BUTTON_DPAD_UP,
	DPAD_DOWN = JOY_BUTTON_DPAD_DOWN,
	DPAD_LEFT = JOY_BUTTON_DPAD_LEFT,
	DPAD_RIGHT = JOY_BUTTON_DPAD_RIGHT,
	MISC1 = JOY_BUTTON_MISC1,
	PADDLE1 = JOY_BUTTON_PADDLE1,
	PADDLE2 = JOY_BUTTON_PADDLE2,
	PADDLE3 = JOY_BUTTON_PADDLE3,
	PADDLE4 = JOY_BUTTON_PADDLE4,
	TOUCHPAD = JOY_BUTTON_TOUCHPAD,
	SDL_MAX = JOY_BUTTON_SDL_MAX,
	MAX = JOY_BUTTON_MAX
}

enum AxisMap
{
	INVALID = JOY_AXIS_INVALID,
	LEFT_X  = JOY_AXIS_LEFT_X,
	LEFT_Y = JOY_AXIS_LEFT_Y,
	RIGHT_X = JOY_AXIS_RIGHT_X,
	RIGHT_Y = JOY_AXIS_RIGHT_Y,
	TRIGGER_LEFT = JOY_AXIS_TRIGGER_LEFT,
	TRIGGER_RIGHT = JOY_AXIS_TRIGGER_RIGHT,
	SDL_MAX = JOY_AXIS_SDL_MAX,
	MAX = JOY_AXIS_MAX
}
