class_name LocalizationMapNames
# Auto generated class made by LocalizationMapGeneratorScript

enum LocalizedID {
	INVALID = -1,
	TITLE,
	MENU_PLAY,
	PINK_TUBERSO_NAME,
	PINK_TUBERSO_DESCRIPTION,
	SATIVUS_NAME,
	SATIVUS_DESCRIPTION,
	GLUMBERRY_NAME,
	GLUMBERRY_DESCRIPTION,
	BLUE_DAUCUS_NAME,
	BLUE_DAUCUS_DESCRIPTION,
	KAARKIDE_FLOWER_NAME,
	KAARKIDE_FLOWER_DESCRIPTION,
	GLOWTUS_FLOWER_NAME,
	GLOWTUS_FLOWER_DESCRIPTION,
	PURTATO_NAME,
	PURTATO_DESCRIPTION,
	TREE_NAME,
	TREE_DESCRIPTION,

}

const TITLE: StringName = &"TITLE"
const MENU_PLAY: StringName = &"MENU_PLAY"
const PINK_TUBERSO_NAME: StringName = &"PINK_TUBERSO_NAME"
const PINK_TUBERSO_DESCRIPTION: StringName = &"PINK_TUBERSO_DESCRIPTION"
const SATIVUS_NAME: StringName = &"SATIVUS_NAME"
const SATIVUS_DESCRIPTION: StringName = &"SATIVUS_DESCRIPTION"
const GLUMBERRY_NAME: StringName = &"GLUMBERRY_NAME"
const GLUMBERRY_DESCRIPTION: StringName = &"GLUMBERRY_DESCRIPTION"
const BLUE_DAUCUS_NAME: StringName = &"BLUE_DAUCUS_NAME"
const BLUE_DAUCUS_DESCRIPTION: StringName = &"BLUE_DAUCUS_DESCRIPTION"
const KAARKIDE_FLOWER_NAME: StringName = &"KAARKIDE_FLOWER_NAME"
const KAARKIDE_FLOWER_DESCRIPTION: StringName = &"KAARKIDE_FLOWER_DESCRIPTION"
const GLOWTUS_FLOWER_NAME: StringName = &"GLOWTUS_FLOWER_NAME"
const GLOWTUS_FLOWER_DESCRIPTION: StringName = &"GLOWTUS_FLOWER_DESCRIPTION"
const PURTATO_NAME: StringName = &"PURTATO_NAME"
const PURTATO_DESCRIPTION: StringName = &"PURTATO_DESCRIPTION"
const TREE_NAME: StringName = &"TREE_NAME"
const TREE_DESCRIPTION: StringName = &"TREE_DESCRIPTION"


static func enum_to_string(id: int) -> StringName:
	match id:
		LocalizedID.TITLE: return TITLE
		LocalizedID.MENU_PLAY: return MENU_PLAY
		LocalizedID.PINK_TUBERSO_NAME: return PINK_TUBERSO_NAME
		LocalizedID.PINK_TUBERSO_DESCRIPTION: return PINK_TUBERSO_DESCRIPTION
		LocalizedID.SATIVUS_NAME: return SATIVUS_NAME
		LocalizedID.SATIVUS_DESCRIPTION: return SATIVUS_DESCRIPTION
		LocalizedID.GLUMBERRY_NAME: return GLUMBERRY_NAME
		LocalizedID.GLUMBERRY_DESCRIPTION: return GLUMBERRY_DESCRIPTION
		LocalizedID.BLUE_DAUCUS_NAME: return BLUE_DAUCUS_NAME
		LocalizedID.BLUE_DAUCUS_DESCRIPTION: return BLUE_DAUCUS_DESCRIPTION
		LocalizedID.KAARKIDE_FLOWER_NAME: return KAARKIDE_FLOWER_NAME
		LocalizedID.KAARKIDE_FLOWER_DESCRIPTION: return KAARKIDE_FLOWER_DESCRIPTION
		LocalizedID.GLOWTUS_FLOWER_NAME: return GLOWTUS_FLOWER_NAME
		LocalizedID.GLOWTUS_FLOWER_DESCRIPTION: return GLOWTUS_FLOWER_DESCRIPTION
		LocalizedID.PURTATO_NAME: return PURTATO_NAME
		LocalizedID.PURTATO_DESCRIPTION: return PURTATO_DESCRIPTION
		LocalizedID.TREE_NAME: return TREE_NAME
		LocalizedID.TREE_DESCRIPTION: return TREE_DESCRIPTION

		_:
			return "INVALID"

static func string_to_enum(id: StringName) -> int:
	match id:
		TITLE: return LocalizedID.TITLE
		MENU_PLAY: return LocalizedID.MENU_PLAY
		PINK_TUBERSO_NAME: return LocalizedID.PINK_TUBERSO_NAME
		PINK_TUBERSO_DESCRIPTION: return LocalizedID.PINK_TUBERSO_DESCRIPTION
		SATIVUS_NAME: return LocalizedID.SATIVUS_NAME
		SATIVUS_DESCRIPTION: return LocalizedID.SATIVUS_DESCRIPTION
		GLUMBERRY_NAME: return LocalizedID.GLUMBERRY_NAME
		GLUMBERRY_DESCRIPTION: return LocalizedID.GLUMBERRY_DESCRIPTION
		BLUE_DAUCUS_NAME: return LocalizedID.BLUE_DAUCUS_NAME
		BLUE_DAUCUS_DESCRIPTION: return LocalizedID.BLUE_DAUCUS_DESCRIPTION
		KAARKIDE_FLOWER_NAME: return LocalizedID.KAARKIDE_FLOWER_NAME
		KAARKIDE_FLOWER_DESCRIPTION: return LocalizedID.KAARKIDE_FLOWER_DESCRIPTION
		GLOWTUS_FLOWER_NAME: return LocalizedID.GLOWTUS_FLOWER_NAME
		GLOWTUS_FLOWER_DESCRIPTION: return LocalizedID.GLOWTUS_FLOWER_DESCRIPTION
		PURTATO_NAME: return LocalizedID.PURTATO_NAME
		PURTATO_DESCRIPTION: return LocalizedID.PURTATO_DESCRIPTION
		TREE_NAME: return LocalizedID.TREE_NAME
		TREE_DESCRIPTION: return LocalizedID.TREE_DESCRIPTION

		_:
			return LocalizedID.INVALID

static func get_all_actions() -> Array[StringName]:
	return [
		TITLE,
		MENU_PLAY,
		PINK_TUBERSO_NAME,
		PINK_TUBERSO_DESCRIPTION,
		SATIVUS_NAME,
		SATIVUS_DESCRIPTION,
		GLUMBERRY_NAME,
		GLUMBERRY_DESCRIPTION,
		BLUE_DAUCUS_NAME,
		BLUE_DAUCUS_DESCRIPTION,
		KAARKIDE_FLOWER_NAME,
		KAARKIDE_FLOWER_DESCRIPTION,
		GLOWTUS_FLOWER_NAME,
		GLOWTUS_FLOWER_DESCRIPTION,
		PURTATO_NAME,
		PURTATO_DESCRIPTION,
		TREE_NAME,
		TREE_DESCRIPTION,

]
