class_name LocalizationMapNames

const TITLE: StringName = &"TITLE"
const MENU_PLAY: StringName = &"MENU_PLAY"
const PINK_TUBERSO_NAME: StringName = &"PINK_TUBERSO_NAME"
const SATIVUS_NAME: StringName = &"SATIVUS_NAME"
const GLUMBERRY_NAME: StringName = &"GLUMBERRY_NAME"
const BLUE_DAUCUS_NAME: StringName = &"BLUE_DAUCUS_NAME"
const KAARKIDE_FLOWER_NAME: StringName = &"KAARKIDE_FLOWER_NAME"
const GLOWTUS_FLOWER_NAME: StringName = &"GLOWTUS_FLOWER_NAME"
const PURTATO_NAME: StringName = &"PURTATO_NAME"
const PINK_TUBERSO_DESCRIPTION: StringName = &"PINK_TUBERSO_DESCRIPTION"
const SATIVUS_DESCRIPTION: StringName = &"SATIVUS_DESCRIPTION"
const GLUMBERRY_DESCRIPTION: StringName = &"GLUMBERRY_DESCRIPTION"
const BLUE_DAUCUS_DESCRIPTION: StringName = &"BLUE_DAUCUS_DESCRIPTION"
const KAARKIDE_FLOWER_DESCRIPTION: StringName = &"KAARKIDE_FLOWER_DESCRIPTION"
const GLOWTUS_FLOWER_DESCRIPTION: StringName = &"GLOWTUS_FLOWER_DESCRIPTION"
const PURTATO_DESCRIPTION: StringName = &"PURTATO_DESCRIPTION"
const TREE_NAME: StringName = &"TREE_NAME"
const TREE_DESCRIPTION: StringName = &"TREE_DESCRIPTION"


static func get_all_actions() -> Array[StringName]:
	return [
		TITLE,
		MENU_PLAY,
		PINK_TUBERSO_NAME,
		SATIVUS_NAME,
		GLUMBERRY_NAME,
		BLUE_DAUCUS_NAME,
		KAARKIDE_FLOWER_NAME,
		GLOWTUS_FLOWER_NAME,
		PURTATO_NAME,
		PINK_TUBERSO_DESCRIPTION,
		SATIVUS_DESCRIPTION,
		GLUMBERRY_DESCRIPTION,
		BLUE_DAUCUS_DESCRIPTION,
		KAARKIDE_FLOWER_DESCRIPTION,
		GLOWTUS_FLOWER_DESCRIPTION,
		PURTATO_DESCRIPTION,
		TREE_NAME,
		TREE_DESCRIPTION,

]
